apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
  namespace: microservices
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http