apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: faketri33/web-shop/user-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: common-env
                  key: JWT_SECRET
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: SPRING_PROFILES_ACTIVE
            - name: R2DBC_URL
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: R2DBC_URL
            - name: R2DBC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: R2DBC_USERNAME
            - name: R2DBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: R2DBC_PASSWORD